openapi: 3.0.1
info:
  title: Content Guardian API
  version: v1
paths:
  /moderate/text:
    post:
      summary: Moderate text content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModerateTextRequest'
      responses:
        '200':
          description: Moderation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModerateTextResponse'
components:
  schemas:
    ModerateTextRequest:
      type: object
      properties:
        content:
          type: string
    ModerateTextResponse:
      type: object
      properties:
        result:
          type: string
          enum: [pass, block]
        reason:
          type: string
