---
services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      - PORT=8083
      - RULES_URL=http://rules:3000
      - GOPROXY=https://proxy.golang.org,direct
      - GOSUMDB=off
    ports:
      - "8083:8083"
    depends_on:
      - rules
    volumes:
      - .:/app

  rules:
    build:
      context: ./apps/rules-engine
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"

  nats:
    image: nats:2.3.4
    ports:
      - 4222:4222
      - 8222:8222

  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: content_guardian
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
